### PR TITLE
Use test-unit gem

### PR DESCRIPTION
**Pull request by hsbt**
I replaced the test-framework to test-unit instead of original framework of ruby/ruby. 

It's easy to maintain rather than the current test-suite.

### CODE REVIEW

**Comment by hsbt** [comment]
@kou @mrkn How about this? I hope to merge and reduce code from deep copy from ruby repo.

**Comment by kou** [comment]
I'll add `assert_*` methods that are used by Fiddle to test-unit and release test-unit.
Please wait for a while.

**Comment by hsbt** [comment]
👍  Thanks. I'll migrate it and using `omit` after that.

**Comment by kou** [comment]
I'll do them too.
You can just wait for my work. :-)

**Comment by hsbt** [comment]
> I'll do them too.

Ah. I means that migration is without fiddle repo like rdoc, irb and etc.

**Comment by kou** [comment]
Ah, I see.

**Comment by hsbt** [comment]
👍

**Comment by kou** [comment]
Done.

**Pull request merged**
